Fix error when no package is specified
Not specifying a package name currently causes an unhelpful error message:
```console
$ spack spec -I ^intel-mkl
Input spec
--------------------------------
==> Error: 'NoneType' object has no attribute 'endswith'
```

This change fixes it so we get a slightly better one:
```console
$ spack spec -I ^intel-mkl
Input spec
--------------------------------
==> Error: Package 'None' not found.
No package name has been specified.
```