patch: Fix clean() for UrlPatch
Calling `spack clean -d mpfr` causes:
```
==> Error: 'UrlPatch' object has no attribute 'stage'
```

Fix this by initializing `self.stage` in `__init__` and checking it in
`clean`.