openblas: fix on M1
Sets a required variable when building on `darwin-monterey-m1`.
Otherwise the following failure is observed:
```
  >> 26641    Undefined symbols for architecture arm64:
     26642      "___chkstk_darwin", referenced from:
     26643          _sgemv_ in libopenblas-r0.3.19.a(sgemv.o)
     26644          _sger_ in libopenblas-r0.3.19.a(sger.o)
     26645          _cblas_sgemv in libopenblas-r0.3.19.a(cblas_sgemv.o)
     26646          _cblas_sger in libopenblas-r0.3.19.a(cblas_sger.o)
     26647          _dgemv_ in libopenblas-r0.3.19.a(dgemv.o)
     26648          _dger_ in libopenblas-r0.3.19.a(dger.o)
     26649          _cblas_dgemv in libopenblas-r0.3.19.a(cblas_dgemv.o)
     26650          ...
     26651    ld: symbol(s) not found for architecture arm64
```