VTK dependency on "mesa" instead of "mesa+llvm"
`vtk` currently has a dependency on `mesa+llvm` when the option `+osmesa` is activated.
Since `vtk` can actually be built simply with `mesa`, I suggest removing the dependency on `+llvm` and leave it to the user to chose whether to install with `llvm` support or not. I suggest this in particular because calling `spack install vtk+osmesa ^mesa+llvm` works when the `vtk` package depends on just `mesa`, while calling `spack install vtk+osmesa ^mesa~llvm` does not work when `vtk` depends on `mesa+llvm`.

Additionally right now, `mesa+llvm` doesn't seem to compile on a standard Debian machine.
(Error reported by spack is the following:
```
gallivm/lp_bld_misc.cpp: In function ‘LLVMOpaqueBuilder* lp_create_builder(LLVMContextRef, lp_float_mode)’:
gallivm/lp_bld_misc.cpp:833:13: error: ‘class llvm::FastMathFlags’ has no member named ‘setUnsafeAlgebra’
```
)