bugfix: concretization shouldn't require concrete packages to be known
Concretization setup was checking all input specs to ensure that we have a `package.py`
on-hand for their dependencies. We don't need a `package.py` for things we aren't going
to build.

When you concretize an environment with a lockfile, *many* of the input specs are
concrete, and we don't need to build them. If a package changes its dependencies, that
shouldn't cause an already-built environment to fail concretization.

A user reported that this was happening with an error like:

```console
spack concretize
==> Error: Package chapel does not depend on py-protobuf@5.28.2/a4rf4glr2tntfwsz6myzwmlk5iu25t74
```

Or, with traceback:
```console
  File "/apps/other/spack-devel/lib/spack/spack/solver/asp.py", line 3014, in setup
    raise spack.spec.InvalidDependencyError(spec.name, missing_deps)
spack.spec.InvalidDependencyError: Package chapel does not depend on py-protobuf@5.28.2/a4rf4glr2tntfwsz6myzwmlk5iu25t74
```

Fix this by skipping the check for concrete input specs. We already ignore conflicts,
etc. for concrete/external specs. If a built package doesn't depend directly on some
package, we shouldn't care about its metadata. And if it does, then we have a package
on-hand.

- [x] Ignore the package existence check for concrete input specs.

Signed-off-by: Todd Gamblin <tgamblin@llnl.gov>