ESMF: set ESMF_LAPACK_LIBPATH if +external-lapack
CC @hzfywhn @AnonNick

This PR set the `ESMF_LAPACK_LIBPATH` variable (from the `lapack` spec
attributes), removing the previous FIXME and commented example.

The original PR for ESMF has those lines and is from 2017:
https://github.com/spack/spack/pull/2831

The comments there describes RPATH issues, but perhaps they've been
solved by now or weren't relevant to this line to begin with?

Without this line, our software compilation (using Fortran fwiw) fails
with link errors, ex:

```
ld: src/esmf.F:73: undefined reference to `esmf_initmod_mp_esmf_initialize_'
```

since the LIBPATH is not set in the `esmf.mk` file.