docs: fix compiler config
It's no longer possible to parent compiler flags under paths:

$ spack concretize -f
Traceback (most recent call last):
  File "/shared/admin/sw-src/rhel6/dynemol/18d7aa2/spack/bin/spack", line 48, in <module>
    sys.exit(spack.main.main())
  File "/shared/admin/sw-src/rhel6/dynemol/18d7aa2/spack/lib/spack/spack/main.py", line 633, in main
    env = ev.find_environment(args)
  File "/shared/admin/sw-src/rhel6/dynemol/18d7aa2/spack/lib/spack/spack/environment.py", line 263, in find_environment
    return Environment(env)
  File "/shared/admin/sw-src/rhel6/dynemol/18d7aa2/spack/lib/spack/spack/environment.py", line 534, in __init__
    self._read_manifest(f)
  File "/shared/admin/sw-src/rhel6/dynemol/18d7aa2/spack/lib/spack/spack/environment.py", line 561, in _read_manifest
    self.yaml = _read_yaml(f)
  File "/shared/admin/sw-src/rhel6/dynemol/18d7aa2/spack/lib/spack/spack/environment.py", line 402, in _read_yaml
    validate(data, filename)
  File "/shared/admin/sw-src/rhel6/dynemol/18d7aa2/spack/lib/spack/spack/environment.py", line 395, in validate
    e, data, filename, e.instance.lc.line + 1)
spack.config.ConfigFormatError: /shared/admin/sw-src/rhel6/dynemol/18d7aa2/spack.yaml:42: Additional properties are not allowed ('cflags' was unexpected)