podman: add macOS support and v5.4.2
Adds macOS support inspired by the homebrew formula. Tested on my laptop
(sequoia 15.3.1) with:

```
podman machine init
podman machine start
podman run -ti node:16-buster-slim
```

Questions:
- not sure if this recipe follows best practices for formatting and flow
- podman requires ≥ ventura. do I list out all the supported OSs as
  requirements (would need to update after each release), or as conflicts (would be a list of 19)?
- podman looks for its tightly coupled deps (gvproxy and vfkit) in a
  set of paths

  ```
  Error: could not find "gvproxy" in one of [$BINDIR/../libexec/podman /usr/local/opt/podman/libexec/podman /opt/homebrew/opt/podman/libexec/podman /opt/homebrew/bin /usr/local/bin /usr/local/libexec/podman /usr/local/lib/podman /usr/libexec/podman /usr/lib/podman].  To resolve this error, set the helper_binaries_dir key in the `[engine]` section of containers.conf to the directory containing your helper binaries.
```

I'm able to get this to work by setting `prefix.bin` path in
`~/.config/containers/containers.conf`, but is there any way to automate
this? I may just need to modify the toml during the install, unless
there's a better option.