Fix missing spack.compiler import
Otherwise, specifying compiler flags on the command line fails with:
Error: 'module' object has no attribute 'compiler'