spack setup: new --shebang option
Allow to specify another shebang in spconfig.py script.

Rationale: `build-env` set PYTHONPATH and PYTHONHOME that can crash other python
interpreter. For instance:
```
[tcarel@lambda]$ spack setup zee@develop

[tcarel@lambda]$ head -n1 spconfig.py
/home/tcarel/src/github.com/pyenv/pyenv/shims/python

[tcarel@lambda]$ spack build-env zee@develop bash --norc

[tcarel@build-env]$ ../spconfig.py ..
Fatal Python error: initfsencoding: unable to load the file system codec
ModuleNotFoundError: No module named 'encodings'

Current thread 0x00007fffedac8740 (most recent call first):
Aborted (core dumped)
```

This kind of issue motivated this patch where the python interpreter
to use is not necessarily the one that has been used to create spconfig.py

A fix for the situation above is: `spack setup --shebang env zee@develop`