util-linux-uuid: add conflict for new version and old compilers
```
util-linux-uuid@2.37.4%gcc@4.8.5 arch=linux-rhel7-haswell
```
results in:
```
libtool: compile:  /projects/spack/lib/spack/env/gcc/gcc -DHAVE_CONFIG_H -I. -include config.h -I./include -DLOCALEDIR=\"/projects/spack/opt/spack/gcc-4.8.5/util-linux-uuid/as7m3v4/share/locale\" -D_PATH_RUNSTATEDIR=\"/projects/spack/opt/spack/gcc-4.8.5/util-linux-uuid/as7m3v4/var/run\" -D_PATH_SYSCONFSTATICDIR=\"/projects/spack/opt/spack/gcc-4.8.5/util-linux-uuid/as7m3v4/lib\" -fsigned-char -fno-common -Wall -Wextra -Wimplicit-function-declaration -Wmissing-declarations -Wmissing-parameter-type -Wmissing-prototypes -Wnested-externs -Wno-missing-field-initializers -Wpointer-arith -Wredundant-decls -Wsign-compare -Wstrict-prototypes -Wtype-limits -Wuninitialized -Wunused-but-set-parameter -Wunused-but-set-variable -Wunused-parameter -Wunused-result -Wunused-variable -Werror=sequence-point -I./libuuid/src -Ilibuuid/src -g -O2 -MT libuuid/src/la-unparse.lo -MD -MP -MF libuuid/src/.deps/la-unparse.Tpo -c libuuid/src/unparse.c  -fPIC -DPIC -o libuuid/src/.libs/la-unparse.o
libuuid/src/unparse.c:42:73: error: expected ';', ',' or ')' before 'fmt'
 static void uuid_fmt(const uuid_t uuid, char *buf, char const *restrict fmt)
```

It looks like it's assuming C99 by default so there may be a better way
to handle this... but this at least works