Trilinos: restrict SuperLU-dist version
SuperLU v6.3.0 changes the name of numerous structures, causing errors
in Amesos up through Trilinos 13.

```
packages/amesos/src/Amesos_Superludist.cpp:50:3: error: 'ScalePermstruct_t' does not name a type; did you mean 'dScalePermstruct_t'?
packages/amesos/src/Amesos_Superludist.cpp:51:3: error: 'LUstruct_t' does not name a type; did you mean 'dLUstruct_t'?
packages/amesos/src/Amesos_Superludist.cpp:52:3: error: 'SOLVEstruct_t' does not name a type; did you mean 'dSOLVEstruct_t'?
packages/amesos/src/Amesos_Superludist.cpp:166:47: error: 'class Amesos_Superlu_Pimpl' has no member named 'ScalePermstruct_'
packages/amesos/src/Amesos_Superludist.cpp:166:5: error: 'ScalePermstructFree' was not declared in this scope
packages/amesos/src/Amesos_Superludist.cpp:167:83: error: 'class Amesos_Superlu_Pimpl' has no member named 'LUstruct_'
packages/amesos/src/Amesos_Superludist.cpp:167:5: error: 'Destroy_LU' was not declared in this scope
packages/amesos/src/Amesos_Superludist.cpp:168:40: error: 'class Amesos_Superlu_Pimpl' has no member named 'LUstruct_'
packages/amesos/src/Amesos_Superludist.cpp:168:5: error: 'LUstructFree' was not declared in this scope
packages/amesos/src/Amesos_Superludist.cpp:170:76: error: 'class Amesos_Superlu_Pimpl' has no member named 'SOLVEstruct_'
packages/amesos/src/Amesos_Superludist.cpp:426:47: error: 'class Amesos_Superlu_Pimpl' has no member named 'ScalePermstruct_'
packages/amesos/src/Amesos_Superludist.cpp:426:5: error: 'ScalePermstructFree' was not declared in this scope
```