curl: explicitly disable unused dependencies
I installed curl on my mac and it picked up a homebrew (I think?)
installation of gsasl. A later system update broke git because of the
implicitly added dependency. Explicitly disabling libraries that *might*
exist on the system is the safe approach here.

```
dyld: Library not loaded: /usr/local/opt/gsasl/lib/libgsasl.7.dylib
  Referenced from: /rnsdhpc/code/spack/opt/spack/apple-clang/curl/gag5v3c/lib/libcurl.4.dylib
  Reason: image not found
error: git-remote-https died of signal 6
```