Update smoke test for new EXAMPLES dir in 5.2.2
Note that the test actually fails in apple-clang%12 due to sloppy C
style:
```
sp_ienv.c:85:5: error: implicit declaration of function 'input_error' is invalid in C99
```