py-torch: Add a breakpad variant, disable it for ppc64 and ppc64le
Breakpad is a new dependency (since pytorch 1.9.0). It doesn't build on
ppc64le:

    FAILED: third_party/breakpad/CMakeFiles/breakpad_common.dir/src/common/linux/breakpad_getcontext.S.o
    spack-src/third_party/breakpad/src/common/linux/ucontext_constants.h:150:2: error: #error "This header has not been ported for your CPU"
    spack-src/third_party/breakpad/src/common/linux/breakpad_getcontext.S:485:2: error: #error "This file has not been ported for your CPU!"

Add a variant to be able to enable/disable it (only possible since pytorch
1.10.0), and disable it by default on ppc64 and ppc64le.