Mark GCC7 and newer as conflicting with rhel6 without binutils
When building gcc7 and gcc8 on RHEL6 with Spack, then installing it as a
spack-available compiler, OpenBLAS will fail to compile because GCC
generates newer instructions than rhel6's `as` assembler knows about:
```
make[1]: *** [dtrsm_kernel_RN_HASWELL.o] Error 1
make[1]: *** Waiting for unfinished jobs....
../kernel/x86_64/dtrmm_kernel_4x8_haswell.c: Assembler messages:
../kernel/x86_64/dtrmm_kernel_4x8_haswell.c:33: Error: no such
instruction: `vpermpd $0x1b,%ymm0,%ymm0'
../kernel/x86_64/dtrmm_kernel_4x8_haswell.c: Assembler messages:
../kernel/x86_64/dtrmm_kernel_4x8_haswell.c:33: Error: no such
instruction: `vpermpd $0x1b,%ymm0,%ymm0'
```

Building gcc8 (I didn't test with gcc7) with binutils succeeds, and it
generates a GCC that can then successfully build OpenBLAS.